### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by balbinosoares** [balbinosoares/relactcapm#1]

**Comment by balbinosoares** [comment]
- [ ] Create Data Model using CDS;
- [ ] Create OData Services for Admin Roles;
- [ ] Create OData Service for Mangers Roles;
- [ ] Create OData Service for Team Member Roles;
- [ ] Add Authentication method
