### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by balbinosoares** [balbinosoares/relactcapm#2]
- [x] Create Data Model using CDS;
- [x] Create OData Services for Admin Roles;
- [ ] Create OData Service for Mangers Roles;
- [ ] Create OData Service for Team Member Roles;
- [ ] Add Authentication method
